### PR TITLE
fix: #3052 variable table container

### LINKED ISSUE #3052: Variant fix table container

### PR DESCRIPTION
**Pull request by francisl**
closes #3052

Screen Shot 2021-04-09 at 12 35 49 AM

### CODE REVIEW

**Review by adipaul1981 — APPROVED** [review]

**Review by evans-g-crsj — APPROVED** [review]

File: src/pages/variantEntity/TabFrequencies.tsx [hunk 1]
```diff
@@ -134,30 +134,34 @@ const TabFrequencies = ({ variantId }: OwnProps) => {
...
+            />
+          </Card>
+          <Card>
+            <Table
+              title={() => 'External Cohorts'}
+              dataSource={makeRowFromFrequencies(frequencies)}
+              columns={externalColumns}
+              pagination={false}
+            />
+          </Card>
```
Comment (adipaul1981) [inline src/pages/variantEntity/TabFrequencies.tsx:164]: I dont know it its better to remove the title from the table and include it into the card instead.

**Review by adipaul1981 — APPROVED** [review]

File: src/pages/variantEntity/TabFrequencies.tsx (hunk 1 above)
Comment (francisl) [reply src/pages/variantEntity/TabFrequencies.tsx:164]: yes, there is still work for the title, so we'll do it in subsequent pr
