### PR TITLE
fix: #3078 studies pagination

### LINKED ISSUE #3078: [Studies] Fix pagination error
When you navigate to another page, then update a filter. The result will be off.

Expect: On filter change, reset page to the first page

### PR DESCRIPTION
**Pull request by francisl**
closes #3078

### CODE REVIEW

File: src/pages/studies/SidebarFilters.tsx [hunk 1]
```diff
@@ -31,9 +31,14 @@ const keyEnhanceBooleanOnly = (key: string) => {
   }
 };
 
-const SidebarFilters = (sidebarData: SidebarData) => {
-  const mappingData = sidebarData.studiesMappingResults;
-  const data = sidebarData.studiesResults;
+type StudiesProps = {
```
Comment (evans-g-crsj) [inline src/pages/studies/SidebarFilters.tsx:34]: same is Sidebar. Could be extracted

File: src/pages/studies/studies.tsx [hunk 2]
```diff
@@ -45,7 +45,11 @@ const Studies = () => {
 
   return (
     <Layout className={styles.layout}>
-      <Sidebar studiesMappingResults={studiesMappingResults} studiesResults={studiesResults} />
+      <Sidebar
+        studiesMappingResults={studiesMappingResults}
+        studiesResults={studiesResults}
+        onChange={() => setCurrentPage(1)}
```
Comment (evans-g-crsj) [inline src/pages/studies/studies.tsx:51]: is that hardcoded value valid?

**Review by evans-g-crsj — APPROVED** [review]

File: src/pages/studies/studies.tsx (hunk 2 above)
Comment (francisl) [reply src/pages/studies/studies.tsx:51]: yes
