### PR TITLE
fix: #3039 remove search in studies

### LINKED ISSUE #3039: Remove Search in filter for studies

### PR DESCRIPTION
**Pull request by francisl**
closes #3039

### CODE REVIEW

File: src/pages/studies/SidebarFilters.tsx [hunk 1]
```diff
@@ -1,18 +1,12 @@
...
-import { Input, Tooltip } from 'antd';
-import { InfoCircleOutlined, SearchOutlined } from '@ant-design/icons';
-
-import { IFilter, IFilterGroup, VisualType } from '@ferlab/ui/core/components/filters/types';
+import { IFilter } from '@ferlab/ui/core/components/filters/types';
 import FilterContainer from '@ferlab/ui/core/components/filters/FilterContainer';
-import { getFilterType, getSelectedFilters, updateFilters, updateQueryFilters } from './utils';
-import { TSqonGroupContent } from '@ferlab/ui/core/components/QueryBuilder/types';
+import { getFilterType, getSelectedFilters, updateFilters } from './utils';
 import { SidebarData } from '../../store/graphql/studies/actions';
```
Comment (evans-g-crsj) [inline src/pages/studies/SidebarFilters.tsx:8]: ../../...

**Review by evans-g-crsj — APPROVED** [review]
